### ISSUE TITLE
Adicionar página de cardápio com tabelas html

### ISSUE THREAD

**Issue by guilherme-gjv** [GabGab-dev/Site-padaria#1]
- Adicione a opção para clicar onde você achar melhor;
    - use a âncora para direcionar ao link da outra página;
- Estude e aplique tabelas de HTML;
- O cardápio tem nome do produto e preço;
- Estilize

**Comment by gabriel-andss** [comment]
Adicionei tabelas de produtos e preços, junto com imagens explicatívas.

![Captura de tela 2022-03-17 172455](https://user-images.githubusercontent.com/100449982/158890320-93b47ebf-722b-496e-bf3c-78978f6900e1.png)
