### ISSUE TITLE
Separar arquivos em pastas

### ISSUE THREAD

**Issue by guilherme-gjv** [GabGab-dev/Site-padaria#2]
- Tá um pouquinho desorganizado, tem muitos arquivos, para diferentes funcionalidades e tudo junto na raiz do projeto;
- Crie as pastas
    - resources (para imagens, e coisas assim);
    - html (para arquivos html)
    - styles (para arquivos CSS)

**⚠️ Detalhes:** 
- Como você tá mudando as pastas, tá mudando também o link, então se atente para mudar nas âncoras, **na importação do css no html**, botões em geral, etc
- Lembra de criar uma branch separada pra dps fazer pull request ksksksksksks

**Comment by gabriel-andss** [comment]
fiz tudo, mas não separei uma branch, eviei tudo ao master
